[2024-09-21T21:30:01.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_empresa scheduled__2024-09-21T21:00:00+00:00 [queued]>
[2024-09-21T21:30:01.563+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_empresa scheduled__2024-09-21T21:00:00+00:00 [queued]>
[2024-09-21T21:30:01.564+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-21T21:30:01.579+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): spark_raw_ingestion_empresa> on 2024-09-21 21:00:00+00:00
[2024-09-21T21:30:01.583+0000] {standard_task_runner.py:57} INFO - Started process 1136 to run task
[2024-09-21T21:30:01.586+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'spark_raw_ingestion_empresa', 'scheduled__2024-09-21T21:00:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmpaa8t4ryu']
[2024-09-21T21:30:01.587+0000] {standard_task_runner.py:85} INFO - Job 391: Subtask spark_raw_ingestion_empresa
[2024-09-21T21:30:01.702+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.spark_raw_ingestion_empresa scheduled__2024-09-21T21:00:00+00:00 [running]> on host airflow-worker
[2024-09-21T21:30:01.892+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='spark_raw_ingestion_empresa' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-21T21:00:00+00:00'
[2024-09-21T21:30:01.892+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-21T21:30:01.893+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-21T21:30:01.920+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-21T21:30:01.921+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-21T21:30:01.928+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-21T21:30:02.059+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-09-21T21:30:02.059+0000] {ssh.py:478} INFO - Running command: export SPARK_HOME=/usr/local/spark; /opt/conda/bin/spark-submit --master local[*] --executor-memory 2g --conf "spark.pyspark.python=/env/venv/bin/python" /opt/shared/scripts/raw_ingestion.py 2024-09-21 empresa
[2024-09-21T21:30:04.329+0000] {ssh.py:529} WARNING - Exception in thread "main" java.io.IOException: Cannot run program "/env/venv/bin/python": error=2, No such file or directory
[2024-09-21T21:30:04.332+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[2024-09-21T21:30:04.333+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[2024-09-21T21:30:04.333+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:97)
[2024-09-21T21:30:04.334+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
[2024-09-21T21:30:04.334+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-09-21T21:30:04.334+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-09-21T21:30:04.335+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-09-21T21:30:04.335+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-09-21T21:30:04.337+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
[2024-09-21T21:30:04.337+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
[2024-09-21T21:30:04.338+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2024-09-21T21:30:04.339+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2024-09-21T21:30:04.339+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2024-09-21T21:30:04.340+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-09-21T21:30:04.341+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-09-21T21:30:04.342+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-09-21T21:30:04.343+0000] {ssh.py:529} WARNING - Caused by: java.io.IOException: error=2, No such file or directory
[2024-09-21T21:30:04.344+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[2024-09-21T21:30:04.344+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[2024-09-21T21:30:04.344+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[2024-09-21T21:30:04.345+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[2024-09-21T21:30:04.345+0000] {ssh.py:529} WARNING - 	... 15 more
[2024-09-21T21:30:04.346+0000] {ssh.py:524} INFO - 24/09/21 21:30:04 INFO ShutdownHookManager: Shutdown hook called
[2024-09-21T21:30:04.346+0000] {ssh.py:524} INFO - 24/09/21 21:30:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-4c241e05-c695-4b37-b363-d4e19d7d9948
[2024-09-21T21:30:04.477+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 166, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 160, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-09-21T21:30:04.481+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=raw_ingestion, task_id=spark_raw_ingestion_empresa, execution_date=20240921T210000, start_date=20240921T213001, end_date=20240921T213004
[2024-09-21T21:30:04.505+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 391 for task spark_raw_ingestion_empresa (SSH operator error: exit status = 1; 1136)
[2024-09-21T21:30:04.532+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-21T21:30:04.602+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
