[2024-09-21T21:07:23.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.trigger_stage_processing manual__2024-09-21T21:07:06.565959+00:00 [queued]>
[2024-09-21T21:07:23.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.trigger_stage_processing manual__2024-09-21T21:07:06.565959+00:00 [queued]>
[2024-09-21T21:07:23.936+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-21T21:07:23.947+0000] {taskinstance.py:1382} INFO - Executing <Task(TriggerDagRunOperator): trigger_stage_processing> on 2024-09-21 21:07:06.565959+00:00
[2024-09-21T21:07:23.951+0000] {standard_task_runner.py:57} INFO - Started process 692 to run task
[2024-09-21T21:07:23.953+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'trigger_stage_processing', 'manual__2024-09-21T21:07:06.565959+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmper391ing']
[2024-09-21T21:07:23.954+0000] {standard_task_runner.py:85} INFO - Job 363: Subtask trigger_stage_processing
[2024-09-21T21:07:24.052+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.trigger_stage_processing manual__2024-09-21T21:07:06.565959+00:00 [running]> on host airflow-worker
[2024-09-21T21:07:24.214+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='trigger_stage_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T21:07:06.565959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T21:07:06.565959+00:00'
[2024-09-21T21:07:24.393+0000] {trigger_dagrun.py:209} INFO - Waiting for stage_processing on 2024-09-21T00:00:00+00:00 to become allowed state ['success'] ...
[2024-09-21T21:08:24.500+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 220, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: stage_processing failed with failed states failed
[2024-09-21T21:08:24.503+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=raw_ingestion, task_id=trigger_stage_processing, execution_date=20240921T210706, start_date=20240921T210723, end_date=20240921T210824
[2024-09-21T21:08:24.519+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 363 for task trigger_stage_processing (stage_processing failed with failed states failed; 692)
[2024-09-21T21:08:24.556+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-21T21:08:24.589+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
