[2024-09-21T20:32:00.185+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T20:00:00+00:00 [queued]>
[2024-09-21T20:32:00.198+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T20:00:00+00:00 [queued]>
[2024-09-21T20:32:00.198+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-21T20:32:00.218+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): spark_raw_ingestion_posicao> on 2024-09-21 20:00:00+00:00
[2024-09-21T20:32:00.224+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2024-09-21T20:32:00.228+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'spark_raw_ingestion_posicao', 'scheduled__2024-09-21T20:00:00+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmp127_89ek']
[2024-09-21T20:32:00.229+0000] {standard_task_runner.py:85} INFO - Job 344: Subtask spark_raw_ingestion_posicao
[2024-09-21T20:32:00.414+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T20:00:00+00:00 [running]> on host airflow-worker
[2024-09-21T20:32:00.771+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='spark_raw_ingestion_posicao' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-21T20:00:00+00:00'
[2024-09-21T20:32:00.772+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-21T20:32:00.772+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-21T20:32:00.822+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-21T20:32:00.824+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-21T20:32:00.837+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-21T20:32:03.230+0000] {transport.py:1893} INFO - Authentication (password) failed.
[2024-09-21T20:32:03.231+0000] {ssh.py:342} INFO - Failed to connect. Sleeping before retry attempt 1
[2024-09-21T20:32:06.742+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-21T20:32:09.140+0000] {transport.py:1893} INFO - Authentication (password) failed.
[2024-09-21T20:32:09.140+0000] {ssh.py:342} INFO - Failed to connect. Sleeping before retry attempt 2
[2024-09-21T20:32:13.975+0000] {transport.py:1893} ERROR - Exception (client): Error reading SSH protocol banner
[2024-09-21T20:32:13.979+0000] {transport.py:1891} ERROR - Traceback (most recent call last):
[2024-09-21T20:32:13.979+0000] {transport.py:1891} ERROR -   File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2292, in _check_banner
[2024-09-21T20:32:13.979+0000] {transport.py:1891} ERROR -     buf = self.packetizer.readline(timeout)
[2024-09-21T20:32:13.980+0000] {transport.py:1891} ERROR -   File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/packet.py", line 374, in readline
[2024-09-21T20:32:13.980+0000] {transport.py:1891} ERROR -     buf += self._read_timeout(timeout)
[2024-09-21T20:32:13.980+0000] {transport.py:1891} ERROR -   File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/packet.py", line 603, in _read_timeout
[2024-09-21T20:32:13.980+0000] {transport.py:1891} ERROR -     raise EOFError()
[2024-09-21T20:32:13.981+0000] {transport.py:1891} ERROR - EOFError
[2024-09-21T20:32:13.981+0000] {transport.py:1891} ERROR - 
[2024-09-21T20:32:13.981+0000] {transport.py:1891} ERROR - During handling of the above exception, another exception occurred:
[2024-09-21T20:32:13.981+0000] {transport.py:1891} ERROR - 
[2024-09-21T20:32:13.982+0000] {transport.py:1891} ERROR - Traceback (most recent call last):
[2024-09-21T20:32:13.982+0000] {transport.py:1891} ERROR -   File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2113, in run
[2024-09-21T20:32:13.982+0000] {transport.py:1891} ERROR -     self._check_banner()
[2024-09-21T20:32:13.983+0000] {transport.py:1891} ERROR -   File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2296, in _check_banner
[2024-09-21T20:32:13.983+0000] {transport.py:1891} ERROR -     raise SSHException(
[2024-09-21T20:32:13.983+0000] {transport.py:1891} ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
[2024-09-21T20:32:13.983+0000] {transport.py:1891} ERROR - 
[2024-09-21T20:32:13.984+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2292, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/packet.py", line 374, in readline
    buf += self._read_timeout(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/packet.py", line 603, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 177, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 142, in get_ssh_client
    return self.hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/hooks/ssh.py", line 346, in get_conn
    for attempt in Retrying(
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/hooks/ssh.py", line 353, in get_conn
    client.connect(**connect_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/client.py", line 451, in connect
    t.start_client(timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 722, in start_client
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2113, in run
    self._check_banner()
  File "/home/airflow/.local/lib/python3.8/site-packages/paramiko/transport.py", line 2296, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
[2024-09-21T20:32:14.014+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=raw_ingestion, task_id=spark_raw_ingestion_posicao, execution_date=20240921T200000, start_date=20240921T203200, end_date=20240921T203214
[2024-09-21T20:32:14.039+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 344 for task spark_raw_ingestion_posicao (Error reading SSH protocol banner; 63)
[2024-09-21T20:32:14.075+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-21T20:32:14.116+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
